### ISSUE TITLE
`d` does not delete the selection

### ISSUE THREAD

**Issue by LemonBreezes** [Not-Leader/doom-meow#15]
We should add `(setq delete-active-region t)` to the config or add that option to the documentation because it is really jarring how by default, `d` does not delete the entire selection.

**Comment by UnchartedSystems** [comment]
Check out meow-tutor! `s`, not `d`, deletes the selection.

**Comment by LemonBreezes** [comment]
> Check out meow-tutor! `s`, not `d`, deletes the selection.

Hey, I'm gonna close this since it's been so long and I'm currently not using Meow but I was using a non-standard keyboard layout and had `d` bound to `meow-delete`.
