### ISSUE TITLE
comint bindings for up/down

### ISSUE THREAD

**Issue by bdarcus** [Not-Leader/doom-meow#3]
Just tested the module, and it's looking good!

One little thing, the details of which I forget in Doom:

Can you add bindings so that, for example, in `ielm` the up and down arrows cycle through the command history?

**Comment by not-leader** [comment]
Can you please elaborate? I'm not sure what you mean by this

**Comment by bdarcus** [comment]
From the help description when using default evil module for `<up>`, where `<down>:` is mapped to `comint-next-input`

```console
<up> runs the command comint-previous-input, which is an interactive native
compiled Lisp function in ‘comint.el’.

It is bound to <up>, C-<up>, <insert-state> <up>, <normal-state> C-p, M-p,
<menu-bar> <inout> <previous-history>.

(comint-previous-input ARG)

Cycle backwards through input history, saving input.
```

But I guess it's fine if it's bound to `C-p` and `C-n`, so fine to close.

**Comment by not-leader** [comment]
oh this kind of stuff is not the type of stuff meow tries to bind to
