### ISSUE TITLE
Keys don't seem to be bound on "recent" doom versions

### ISSUE THREAD

**Issue by aisamu** [Not-Leader/doom-meow#7]
I've tried the recommended configuration both on my personal config and on a clean doom install:
```diff
  :editor
+ (meow +qwerty +override +keypad)
- evil

```
Invoking `meow-tutor` (via `M-x`), gives:
```
==================================================================
=                     BASIC CURSOR MOVEMENT                      =
==================================================================

  To move up, press M-x meow-prev
  To move down, press M-x meow-next
  To move left, press M-x meow-left
  To move right, press M-x meow-right
       ↑
       M-x meow-prev
   ← M-x meow-left   M-x meow-right →
       M-x meow-next
       ↓
```

It appears that the keybindings are not being picked up!
I'm still very eager to test it out - thanks for taking the time to create this module for the rest of us!

#### Versions
* Emacs: `GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.3.0, NS appkit-2113.30 Version 12.2.1 (Build 21D62))`
* Doom-meow: meow-edit/doom-meow@5078d0a58baa0621b93cd9d18a80412d16c0ce56
* Doom: doomemacs/doomemacs@58fb83c98eac32fc77710ee2f6bcfb3a86f7b6fb

**Comment by jsjoberg** [comment]
I was in the same situation. Solved it by adding (defun meow-setup () ...), (meow-setup), (meow-global-mode 1) to ~/.doom.d/config.el.

**Comment by Not-Leader** [comment]
okay
